fix: make entire select box clickable
techmatters/terraso-mobile-client pull request #1443
Opened 2024-05-29 18:05 UTC by paulschreiber

## Description
Make entire select box clickable on IOS.

### Related Issues
Addresses #1313.

2024-05-29 18:16 UTC, shrouxm requested changes
i believe the intention is for the label to still be visible when the dropdown is selected, which this code doesn't seem to do?

2024-06-06 22:04 UTC, knipec commented
Re: Garo's comment 
> i believe the intention is for the label to still be visible when the dropdown is selected, which this code doesn't seem to do?

Could be worth a quick checkin with Courtney if it's desired to move the label, since there's already a title "Add to Project" right above it, so it seems kinda redundant.

2024-06-06 22:18 UTC, knipec approved these changes
Approving assuming the answer to my question is "yup", and Courtney is good with the label stuff :)

2024-06-06 22:18 UTC, knipec commented on dev-client/__tests__/integration/__snapshots__/CreateSiteScreen-test.tsx.snap
Question: Do you understand why there are a few levels of `<View>` that are no longer in the snapshot? Is it because `<TextInput>` is implemented with nested `<View>`s whereas `<Row>` is not?

2024-06-07 00:27 UTC, paulschreiber commented
@knipec The label and placeholder placement was discussed with/designed by Courtney.

2024-06-07 00:27 UTC, paulschreiber commented on dev-client/__tests__/integration/__snapshots__/CreateSiteScreen-test.tsx.snap
No idea how these components are implemented behind the scenes.

2024-06-07 00:56 UTC, merged