chore: Add env setup instructions to README
techmatters/terraso-mobile-client pull request #180
Opened 2023-07-11 19:29 UTC by david-code

## Description

Adds info for setting up mobile env

2023-07-11 20:22 UTC, paulschreiber requested changes

2023-07-11 20:22 UTC, paulschreiber commented on README.md
> +2. Copy `.env.sample` to `.env`. You need to change the `GOOGLE_OAUTH_APP_CLIENT_ID` variable to match
Please clarify `change to match`.

2023-07-11 20:22 UTC, paulschreiber commented on README.md
> +Once all of the dependencies are installed, the first barrier to running the project locally is getting past the login screen. In order to do so, you'll need to do the following:
```suggestion
Once all of the dependencies are installed, you'll need to do the following to enable logins:
```

2023-07-12 14:44 UTC, paulschreiber approved these changes

2023-07-12 14:44 UTC, paulschreiber commented on README.md
> +2. Copy `.env.sample` to `.env`. You need to change the `GOOGLE_OAUTH_APP_CLIENT_ID` variable to match the value of your OAuth App client id
```suggestion
2. Copy `.env.sample` to `.env`. Change `GOOGLE_OAUTH_APP_CLIENT_ID` variable to match the value of your OAuth App client ID in Google Cloud Console.
```

2023-07-12 16:41 UTC, shrouxm approved these changes
LGTM, i will give it a whirl when i'm doing my next home screen PR!

2023-07-12 17:48 UTC, merged