feat: add soil cracking section to site data
techmatters/terraso-mobile-client pull request #2565
Opened 2024-11-27 20:00 UTC by paulschreiber

## Description
Add a soil cracking section to the site data screen.

### Related Issues
Addresses https://github.com/techmatters/terraso-mobile-client/issues/1888

2024-11-27 22:09 UTC, tm-ruxandra requested changes
Requires PO file update

2024-12-04 00:25 UTC, knipec approved these changes
Seems good after addressing the comments

2024-12-04 00:25 UTC, knipec commented on dev-client/src/screens/LocationScreens/components/soilId/SiteSoilCracksSection.tsx
> +        <></>
Design nit: The Figma has the spacing consistent regardless of if there's data there or not. This change has them slightly different. Just want to make sure Courtney doesn't mind this?

![Screenshot 2024-12-03 at 4 17 27 PM](https://github.com/user-attachments/assets/55397c9f-18be-4d97-b6a2-2128927850d6) vs ![Screenshot 2024-12-03 at 4 17 46 PM](https://github.com/user-attachments/assets/70bf174b-9be5-4acb-ba6e-c81304b4bad6)

2024-12-04 14:09 UTC, CourtneyLee333 commented
I don't mind. Thanks for checking!

2024-12-04 15:08 UTC, merged